name: Pull Request Checks

on:
  pull_request:
    branches: ['**']

jobs:
  quality-checks:
    name: Code Quality & Tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Lint check
        run: npm run lint

      - name: Type check
        run: npx tsc --noEmit

      - name: Run tests with coverage (thorough mode with real timers)
        run: npx cross-env TEST_REAL_TIMERS=true npm run test:coverage

      - name: Build verification
        run: npm run build

      - name: Check bundle size
        run: |
          BUNDLE_SIZE=$(du -sb dist | cut -f1)
          MAX_SIZE=$((5 * 1024 * 1024))
          BUNDLE_SIZE_MB=$(($BUNDLE_SIZE / 1024 / 1024))
          echo "📦 Bundle size: ${BUNDLE_SIZE_MB}MB"

          if [ $BUNDLE_SIZE -gt $MAX_SIZE ]; then
            echo "❌ Bundle size (${BUNDLE_SIZE_MB}MB) exceeds 5MB limit!"
            exit 1
          else
            echo "✅ Bundle size within 5MB limit"
          fi

      - name: Upload test coverage
        uses: actions/upload-artifact@v3
        if: always()
        with:
          name: coverage-report
          path: coverage/

      - name: Comment PR with results
        uses: actions/github-script@v7
        if: always()
        with:
          script: |
            const fs = require('fs');
            const bundleSize = fs.statSync('dist').size;
            const bundleSizeMB = (bundleSize / 1024 / 1024).toFixed(2);

            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: `## ✅ PR Checks Passed

              - ✓ Lint check
              - ✓ Type check
              - ✓ All tests passed
              - ✓ Build successful
              - 📦 Bundle size: ${bundleSizeMB}MB / 5MB`
            });
